version: '3'

networks:
  database1_network:
    driver: bridge

volumes:
  database1_volume:

x-environment: &environment
  environment:
    POSTGRES_DB: exercise_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
services:
  db:
    image: postgres:13.3
    <<: *environment
    volumes:
      - database1_volume:/var/lib/postgresql/data
    networks:
      - database1_network
  

  init:
    build:
      context: ./
      dockerfile: api.dev.Dockerfile
    container_name: nest_app
    image:  exercise-nest:latest
    working_dir: /mnt/app
    <<: *environment
    networks: 
      - database1_network
    volumes:
      - ./api:/mnt/app
      - /mnt/app/node_modules/
    depends_on: 
      - db
    command: >
      sh -c 'yarn db:sync'
  test-unit:
    build:
      context: ./
      dockerfile: api.dev.Dockerfile
    container_name: nest_app
    image:  exercise-nest:latest
    working_dir: /mnt/app
    <<: *environment
    networks: 
      - database1_network
    volumes:
      - ./api:/mnt/app
      - /mnt/app/node_modules/
    depends_on: 
      - db
    command: >
      sh -c 'yarn test:e2e'
  test-build:
    build:
      context: ./
      dockerfile: api.dev.Dockerfile
    container_name: nest_app
    image:  exercise-nest:latest
    working_dir: /mnt/app
    <<: *environment
    networks: 
      - database1_network
    volumes:
      - ./api:/mnt/app
      - /mnt/app/node_modules/
    depends_on: 
      - db
    command: >
      sh -c 'yarn build' 