version: '3'

networks:
  database1_network:
    driver: bridge

volumes:
  database1_volume:
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database1_volume:/var/lib/postgresql/data
    networks:
      - database1_network
  
  pgadmin4:
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
        - 8002:80
    networks:
      - database1_network