version: '3'

networks:
  database1_network:
    driver: bridge

volumes:
  database1_volume:

x-environment: &environment
  environment:
    POSTGRES_DB: exercise_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432

x-schematest: &schema-test
  build:
    context: ./
    dockerfile: api.dev.Dockerfile
  container_name: nest_app
  image:  exercise-nest:latest
  working_dir: /mnt/app
  <<: *environment
  networks: 
    - database1_network
  volumes:
    - ./api:/mnt/app
    - /mnt/app/node_modules/
  depends_on: 
    - db

services:
  db:
    image: postgres:13.3
    <<: *environment
    volumes:
      - database1_volume:/var/lib/postgresql/data
    networks:
      - database1_network
  
  init:
    <<: *schema-test
    command: >
      sh -c 'yarn db:sync'
  test-unit:
    <<: *schema-test
    command: >
      sh -c 'yarn test:e2e'
  test-build:
    <<: *schema-test
    command: >
      sh -c 'yarn build' 